In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("남양주_총점_충전량_결합.csv", encoding = 'CP949')
df.head(8)

,gid,건물1,건물2,건물3,도서관,민원행정기,변압기,전기안전관,전기차,교통량,경제인구,주차면수,총점,Rank,총이용수,총충전량,일평균충전,일평균이용
0,다사73bb67ba,0.052632,0.0,0,0.044776,0.0,0.012195,0.000000,0.0,0.000000,0.062616,0.000000,0.287467,2049,NaN,NaN,NaN,NaN
1,다사85ab65ba,0.026316,0.0,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.052632,3148,NaN,NaN,NaN,NaN
2,다사82ab57ba,0.144737,0.0,0,0.059701,0.0,0.000000,0.000000,0.0,0.000001,0.000000,0.000000,0.349178,1834,NaN,NaN,NaN,NaN
3,다사70ab68aa,0.026316,0.0,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.052632,3148,NaN,NaN,NaN,NaN
4,다사86aa66aa,0.078947,0.0,0,0.149254,0.0,0.008130,0.000000,0.0,0.012302,0.000000,0.000000,0.339883,1866,NaN,NaN,NaN,NaN
5,다사72aa57bb,0.263158,0.0,0,0.089552,0.0,0.016260,0.033333,0.0,0.106313,0.008060,0.000000,0.960873,861,NaN,NaN,NaN,NaN
6,다사74ab71ba,0.026316,0.0,0,0.029851,0.0,0.036585,0.000000,0.0,0.000000,0.004030,0.465116,0.127127,2732,NaN,NaN,NaN,NaN
7,다사82bb58ab,0.013158,0.0,0,0.000000,0.0,0.008130,0.000000,0.0,0.000000,0.002170,0.000000,0.038786,3280,NaN,NaN,NaN,NaN

In [ ]:
'''
건물1 : 1
건물2 : 2
건물3 : 3

도서관 : 1
민원행정기관 : 1

변압기 : 1
전기안전관리자 : 1
전기차 : 3

교통량 : 2
경제인구 : 2
주차면수 : 2
'''

In [ ]:
weight = [1,2,3,1,1,1,1,3,2,2,2]

In [3]:
df2 = df.fillna(0)

df2.head(10)

,gid,건물1,건물2,건물3,도서관,민원행정기,변압기,전기안전관,전기차,교통량,경제인구,주차면수,총점,Rank,총이용수,총충전량,일평균충전,일평균이용
0,다사73bb67ba,0.052632,0.0,0,0.044776,0.0,0.012195,0.000000,0.0,0.000000,0.062616,0.000000,0.287467,2049,0.0,0.0,0.0,0.0
1,다사85ab65ba,0.026316,0.0,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.052632,3148,0.0,0.0,0.0,0.0
2,다사82ab57ba,0.144737,0.0,0,0.059701,0.0,0.000000,0.000000,0.0,0.000001,0.000000,0.000000,0.349178,1834,0.0,0.0,0.0,0.0
3,다사70ab68aa,0.026316,0.0,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.052632,3148,0.0,0.0,0.0,0.0
4,다사86aa66aa,0.078947,0.0,0,0.149254,0.0,0.008130,0.000000,0.0,0.012302,0.000000,0.000000,0.339883,1866,0.0,0.0,0.0,0.0
5,다사72aa57bb,0.263158,0.0,0,0.089552,0.0,0.016260,0.033333,0.0,0.106313,0.008060,0.000000,0.960873,861,0.0,0.0,0.0,0.0
6,다사74ab71ba,0.026316,0.0,0,0.029851,0.0,0.036585,0.000000,0.0,0.000000,0.004030,0.465116,0.127127,2732,0.0,0.0,0.0,0.0
7,다사82bb58ab,0.013158,0.0,0,0.000000,0.0,0.008130,0.000000,0.0,0.000000,0.002170,0.000000,0.038786,3280,0.0,0.0,0.0,0.0
8,다사63ba66bb,0.000000,0.0,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,3568,0.0,0.0,0.0,0.0
9,다사76ab72ab,0.276316,0.0,0,0.298507,0.0,0.004065,0.033333,0.0,0.000960,0.000000,0.000000,0.957123,863,0.0,0.0,0.0,0.0

In [ ]:
df_y = df2

In [ ]:
for i in range(len(df_y)) :
    for j in range(1,12,1) :
        df_y.iloc[i,j] = ( df_y.iloc[i,j] - min(df_y.iloc[:, j]) )/ ( max(df_y.iloc[:,j]) - min(df_y.iloc[:, j]) )
df_y.head()

In [ ]:
df2 = df_y

In [ ]:
score = []
for i in range(len(df2)) :
    score.append(0)

    for j in range(1,12,1) :
        score[i] += df2.iloc[i, j] * weight[j-1]
        
df2['총점'] = score

In [ ]:
df2.head()

In [ ]:
df2['Rank'] = df2['총점'].rank(ascending = False, method = 'min')

In [ ]:
df2.head()

In [ ]:
print( max(df2['경제인구']), min(df2['경제인구']))

In [ ]:
df_y = df2

In [ ]:
df_y.head()

In [ ]:
df2.sort_values( ["Rank"], ascending = True ).head()

In [ ]:
df2.sort_values( ["총점"], ascending =  False ).head()

In [ ]:
max(df_y.iloc[:, 10])